server:
  port: 8775

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  security:
    enabled: false

spring:
  boot:
    admin:
      discovery:
        ignored-services: tc-platform-admin
  rabbitmq:
    username: admin
    password: admin
    port: 5672
    host: 192.168.1.109
  datasource:
    url: jdbc:mysql://192.168.1.109:3306/ZIPKIN?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    data-username: root
    data-password: root
    driver-class-name: com.mysql.jdbc.Driver
    initialize: false
    continue-on-error: true

sleuth:
    enabled: false

zipkin:
  storage:
    type: mysql
